export const LOGIN_CONSTANTS = {
  TITLE: 'Welcome back',
  SUBTITLE: 'Sign in to pick up where your last note left off.',
  GOOGLE_BUTTON_TEXT: 'Continue with Google',
  DIVIDER_TEXT: 'OR',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'you@example.com',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: '••••••••',
  REMEMBER_ME_LABEL: 'Remember me',
  FORGOT_PASSWORD_LINK: 'Forgot password?',
  SUBMIT_BUTTON_TEXT: 'Sign in',
  SUBMIT_BUTTON_LOADING: 'Signing in...',
  NEW_HERE_TEXT: 'New here?',
  CREATE_ACCOUNT_LINK: 'Create an account',
  TERMS_NOTICE_PREFIX: 'By signing in you agree to our',
  TERMS_LINK: 'Terms of Service',
  AND_TEXT: 'and',
  PRIVACY_LINK: 'Privacy Policy.',
};
