export const SIGNUP_CONSTANTS = {
  TITLE: 'Create your account',
  SUBTITLE: 'Takes about thirty seconds.',
  GOOGLE_BUTTON_TEXT: 'Continue with Google',
  DIVIDER_TEXT: 'OR',
  NAME_LABEL: 'Full name',
  NAME_PLACEHOLDER: 'Ada Lovelace',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'you@example.com',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'At least 8 characters',
  TERMS_CHECKBOX_PREFIX: 'I agree to the',
  TERMS_LINK: 'Terms of Service',
  AND_TEXT: 'and',
  PRIVACY_LINK: 'Privacy Policy',
  SUBMIT_BUTTON_TEXT: 'Create account',
  SUBMIT_BUTTON_LOADING: 'Creating account...',
  ALREADY_HAVE_ACCOUNT_TEXT: 'Already have an account?',
  SIGN_IN_LINK: 'Sign in',
};
